# Generated by Django 5.0.4 on 2024-06-23 17:31

from django.db import migrations


def create_unique_brands(apps, schema_editor):
    shoe = apps.get_model('main_app', 'Shoe')
    unique_brands = apps.get_model('main_app', 'UniqueBrands')

    # We get all the distinct brand names from the shoe table
    unique_brands_names = shoe.objects.values_list('brand', flat=True).distinct()

    # We create instances for every unique brand name
    unique_brands_to_create = [unique_brands(brand_name=brand_name) for brand_name in unique_brands_names]

    # We take the list of instances and submit them at once
    unique_brands.objects.bulk_create(unique_brands_to_create)

    # for brand_name in unique_brands_names:
    #     unique_brands.create(brand_name=brand_name)


def delete_unique_brands(apps, schema_editor):
    unique_brands = apps.get_model('main_app', 'UniqueBrands')

    # We delete all rows in the table - same as TRUNCATE
    unique_brands.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_uniquebrands'),
    ]

    operations = [
        migrations.RunPython(create_unique_brands, reverse_code=delete_unique_brands)
    ]
