# Generated by Django 5.0.4 on 2024-06-24 19:25

from django.db import migrations


def set_price(apps, schema_editor):
    PRICE_MULTIPLIER = 120

    smartphone_model = apps.get_model('main_app', 'Smartphone')

    all_smartphones = smartphone_model.objects.all()

    for smartphone in all_smartphones:
        smartphone.price = len(smartphone.brand) * PRICE_MULTIPLIER

    smartphone_model.objects.bulk_update(all_smartphones, ['price'])


def set_category(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')

    all_smartphones = smartphone_model.objects.all()

    for smartphone in all_smartphones:
        if smartphone.price >= 750:
            smartphone.category = 'Expensive'
        else:
            smartphone.category = 'Cheap'

    smartphone_model.objects.bulk_update(all_smartphones, ['category'])


def set_price_and_category(apps, schema_editor):
    set_price(apps, schema_editor)
    set_category(apps, schema_editor)


def set_price_category_default(apps, schema_editor):
    smartphone_model = apps.get_model('main_app', 'Smartphone')

    all_smartphones = smartphone_model.objects.all()

    default_smartphone_price = smartphone_model._meta.get_field('price').default
    default_smartphone_category = smartphone_model._meta.get_field('category').default

    for smartphone in all_smartphones:
        smartphone.price = default_smartphone_price
        smartphone.category = default_smartphone_category

    smartphone_model.objects.bulk_update(all_smartphones, ['price'])
    smartphone_model.objects.bulk_update(all_smartphones, ['category'])


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_smartphone'),
    ]

    operations = [
        migrations.RunPython(set_price_and_category, reverse_code=set_price_category_default)
    ]
