# Generated by Django 5.0.4 on 2024-06-25 06:10

from django.db import migrations
from django.utils import timezone


def update_delivery_warranty(apps, schema_editor):
    order_model = apps.get_model('main_app', 'Order')

    all_orders = order_model.objects.all()
    orders_to_delete = []

    for order in all_orders:
        if order.status == 'Pending':
            order.delivery = order.order_date + timezone.timedelta(days=3)
        elif order.status == 'Completed':
            order.warranty = '24 months'
        elif order.status == 'Cancelled':
            orders_to_delete.append(order)

    order_model.objects.bulk_update(all_orders, ['delivery', 'warranty'])

    for order in orders_to_delete:
        order.delete()


def reverse_deliver_and_warranty(apps, schema_editor):
    order_model = apps.get_model('main_app', 'Order')

    all_orders = order_model.objects.all()

    for order in all_orders:
        if order.status == 'Pending':
            order.delivery = None
        elif order.status == 'Completed':
            order.warranty = 'No warranty'

    order_model.objects.bulk_update(all_orders, ['delivery', 'warranty'])


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_order'),
    ]

    operations = [
        migrations.RunPython(update_delivery_warranty, reverse_code=reverse_deliver_and_warranty)
    ]
